python:
  - "2.7"
  
script:
  - mbed compile -t GCC_ARM -m NUCLEO_F429ZI --profile azure_debug.json -c
  - mbed compile -t GCC_ARM -m K64F --profile azure_debug.json -c

before_install:
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-arm-none-eabi --force-yes
  # Print versions we use
  - arm-none-eabi-gcc --version
  - python --version

install:
  - pip install mbed-cli 